# Generated by Django 5.1.6 on 2025-02-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonymodel',
            name='dob',
            field=models.DateField(),
        ),
    ]
